version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: clubdb
  app:
    image: bookclub-backend
    ports:
      - "13000:3000"