services:
  db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: clubdb

  bookclub-backend:
    container_name: bookclub-backend
    build:
      context: .
      dockerfile: Dockerfile
    image: bookclub-backend
    environment:
      - DATABASE_URL=postgresql://username:password@db:5432/clubdb
      - POSTGRES_HOST=db
      - POSTGRES_PASSWORD=password
      - REQUEST_ORIGIN=localhost:3003
    ports:
      - "13000:3003"
    depends_on:
      - db
