apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    alpha.image.policy.openshift.io/resolve-names: "*"
    image.openshift.io/triggers: >-
      [{"from":{"kind":"ImageStreamTag","name":"bookclub:staging","namespace":"bookclub-ohtu-k2026"},"fieldPath":"spec.template.spec.containers[?(@.name==\"bookclub\")].image","pause":"false"}]
  name: bookclub-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookclub
  template:
    metadata:
      labels:
        app: bookclub
    spec:
      containers:
        - name: bookclub
          image: bookclub:staging
          ports:
            - containerPort: 3003
          env:
           - name: DATABASE_URL
             valueFrom:
              configMapKeyRef:
                name: bookclub-config
                key: DATABASE_URL