# STAGING SERVICE
apiVersion: v1
kind: Service
metadata:
  name: bookclub-staging
spec:
  selector:
    app: bookclub
    env: staging
  ports:
    - protocol: TCP
      port: 3003
      targetPort: 3003
  type: ClusterIP

---

# PRODUCTION SERVICE
apiVersion: v1
kind: Service
metadata:
  name: bookclub-prod
spec:
  selector:
    app: bookclub
    env: prod
  ports:
    - protocol: TCP
      port: 3003
      targetPort: 3003
  type: ClusterIP