CREATE TABLE "User" (
	"id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	"email" TEXT,
	"name" TEXT,
	"password_hash" TEXT
);

CREATE TABLE "BookClub" (
	"id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	"name" TEXT,
	"status" INTEGER,
	"owner_id" INTEGER REFERENCES "User"("id")
);
-- lisää bookclubiin jäsenet

CREATE TABLE "Invite" (
	"id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	"bookclub_id" INTEGER REFERENCES "BookClub"("id"),
	"invite_code" TEXT
);
-- Yhistä invite bookclubiin

CREATE TABLE "BookClubMembers" (
	"id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	"user_id" INTEGER REFERENCES "User"("id"),
	"user_role" INTEGER,
	"bookclub_id" INTEGER REFERENCES "BookClub"("id")
);

CREATE TABLE "Book" (
	"isbn" TEXT PRIMARY KEY,
	"name" TEXT,
	"author" TEXT,
	"year" TEXT,
	"pages" TEXT,
	"comment" TEXT,
	"language" TEXT,
	"genre" TEXT
);

CREATE TABLE "BookSaved" (
	"id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	"user_id" INTEGER REFERENCES "User"("id"),
	"book_isbn" TEXT REFERENCES "Book"("isbn")
);

CREATE TABLE "BooksInCycle" (
	"id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	"book_isbn" TEXT REFERENCES "Book"("isbn"),
	"user_id" INTEGER REFERENCES "User"("id"),
	"bookclub_id" INTEGER REFERENCES "BookClub"("id"),
	"score" INTEGER
);

-- Lisää äänestystaulu (ks. tapaamisen muistiinpanot kohta "Äänestyssykli").
