ARG NODE_VERSION=24.14.0

FROM node:${NODE_VERSION} AS dev

# Set working directory inside the container
WORKDIR /app

# Copy package files
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy rest of the source code
COPY . .



# Expose backend port
EXPOSE 3003

# Run backend in dev mode with file watching
CMD ["npm", "run", "dev"]
