name: Test

on:
  push:
  pull_request:
  workflow_call:

jobs:
  test-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Node
        uses: actions/setup-node@v6
        with:
          node-version: '26'

      - name: Install backend dependencies
        working-directory: bookclub-backend
        run: npm ci

      - name: Generate Prisma types
        working-directory: bookclub-backend
        env:
          DATABASE_URL: "postgresql://dummy:dummy@localhost/dummy"
        run: npx prisma generate

      - name: Test backend
        working-directory: bookclub-backend
        run: npm run test

  test-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Node
        uses: actions/setup-node@v6
        with:
          node-version: '26'

      - name: Install frontend dependencies
        working-directory: bookclub-front
        run: npm ci

      - name: Test frontend
        working-directory: bookclub-front
        run: npm run test